spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  output:
    ansi:
      enabled: detect
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: tracker_nlp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tracker_nlp?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tracker_nlp
    password: 397773106
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 500000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    banner-mode: console
  profiles:
    active: default
    include: aliyun,storage
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 50  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 25      # 连接池中的最大空闲连接
        min-idle: 10       # 连接池中的最小空闲连接
  mail:
    host: smtp.qq.com
    username: finger@spianmo.com
    password: xsvvrfwunyclcach
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kaptcha:
    store: session

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.njnu.collection.backend.pojo,cn.edu.njnu.collection.backend.vo


logging:
  level:
    root: info
    com:
      itheima:
        admin:
          mapper: debug

upload:
  ossType: LocalStorage #AliYunOss
  image: png,jpg,gif,bmp

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  tomcat:
    uri-encoding: utf-8
  port: 9090
  servlet:
    context-path: /api